name: Build & publish to deploy branch

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # KHÔNG cấu hình cache để tránh lỗi khi thiếu lock file

      - name: Enable Corepack (yarn/pnpm)
        run: corepack enable

      # --- Install deps theo lock file hiện có ---
      - name: Use pnpm
        if: hashFiles('**/pnpm-lock.yaml') != ''
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install (pnpm)
        if: hashFiles('**/pnpm-lock.yaml') != ''
        run: pnpm install --frozen-lockfile

      - name: Install (yarn)
        if: hashFiles('**/yarn.lock') != ''
        run: yarn install --frozen-lockfile

      - name: Install (npm ci)
        if: hashFiles('**/package-lock.json') != ''
        run: npm ci

      - name: Install (npm, no lock)
        if: hashFiles('**/package-lock.json') == '' && hashFiles('**/yarn.lock') == '' && hashFiles('**/pnpm-lock.yaml') == ''
        run: npm install

      # --- Build ---
      - name: Build
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm build;
          elif [ -f yarn.lock ]; then yarn build;
          else npm run build; fi

      # Đưa .cpanel.yml vào dist để branch deploy có file ở ROOT
      - name: Include .cpanel.yml
        run: cp .cpanel.yml dist/. || true

      # Publish nội dung dist lên branch deploy (ở ROOT)
      - name: Publish to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./dist
          keep_files: false
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
