name: Build & publish to deploy branch

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # đưa .cpanel.yml vào dist để branch deploy có file ở ROOT
      - name: Include .cpanel.yml
        run: cp .cpanel.yml dist/. || true

      # publish nội dung dist lên branch deploy (ở ROOT)
      - name: Publish to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./dist
          keep_files: false
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
